services:
  backend:
    build: 
      context: .
      args:
        BUILD_ENV: 'dev'

    ports:
      - 8000:8000

    depends_on:
      - database

    env_file: .env.example

    command: |
      /bin/sh -c "
        cp .env.example .env &&
        uv run manage.py migrate --no-input &&
        # uv run manage.py collectstatic --no-input &&
        uv run opentelemetry-instrument python manage.py runserver 0.0.0.0:8000 --noreload
      "

  database:
    image: postgres:17.6-alpine3.21
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: over_engineered

    volumes:
      - db_data:/var/lib/postgresql/data


volumes:
  db_data:

