name: Code Checks
on:
  push:
    branches:
      - "feature/adding-pre-commit-hook-gh-action"
#  workflow_run:
#    workflows: ["Build and push images to DockerHub", "Build images that are tagged"]
#    types:
#      - requested

jobs:
  run-pre-commit-hook-check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up the repo locally
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Run precommit hook
        uses: pre-commit/action@v3.0.1
