name: Deploy to Azure Container App service
on: 
  push:
    branches:
      - feature/direct_deployment_to_azure_container_apps
#  workflow_run:
#    workflows:
#      - Build and push images to DockerHub
#    types:
#      - completed
#
permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

